// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SistemaFinanciero.Data;

#nullable disable

namespace SistemaFinanciero.Migrations
{
    [DbContext(typeof(FinancialDbContext))]
    [Migration("20260927002809_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SistemaFinanciero.Models.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountNumber")
                        .HasColumnType("text");

                    b.Property<int>("AccountType")
                        .HasColumnType("integer");

                    b.Property<string>("BankName")
                        .HasColumnType("text");

                    b.Property<string>("CardLastDigits")
                        .HasColumnType("text");

                    b.Property<string>("Clabe")
                        .HasColumnType("text");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LongDescription")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "Name")
                        .IsUnique();

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("53890490-08ae-4208-aefa-b78066b96f93"),
                            AccountType = 2,
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 9, 27, 0, 28, 9, 198, DateTimeKind.Utc).AddTicks(3229),
                            IsActive = true,
                            Name = "Caja Chica",
                            UpdatedAt = new DateTime(2026, 9, 27, 0, 28, 9, 198, DateTimeKind.Utc).AddTicks(3229)
                        },
                        new
                        {
                            Id = new Guid("a51b0c0f-2cec-4d8a-a4db-5e125d60a29b"),
                            AccountType = 0,
                            BankName = "Banamex",
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 9, 27, 0, 28, 9, 198, DateTimeKind.Utc).AddTicks(3229),
                            IsActive = true,
                            Name = "Cuenta Operativa",
                            UpdatedAt = new DateTime(2026, 9, 27, 0, 28, 9, 198, DateTimeKind.Utc).AddTicks(3229)
                        },
                        new
                        {
                            Id = new Guid("c7e3800d-7e09-4de6-967c-a5c967a267c8"),
                            AccountType = 4,
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 9, 27, 0, 28, 9, 198, DateTimeKind.Utc).AddTicks(3229),
                            IsActive = true,
                            Name = "Fondo de Inversión",
                            UpdatedAt = new DateTime(2026, 9, 27, 0, 28, 9, 198, DateTimeKind.Utc).AddTicks(3229)
                        });
                });

            modelBuilder.Entity("SistemaFinanciero.Models.Concept", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<int>("ConceptType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LongDescription")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "ConceptType", "Name")
                        .IsUnique();

                    b.ToTable("Concepts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("624c8b1a-b5ee-491d-9543-eaa83bb32d73"),
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ConceptType = 0,
                            CreatedAt = new DateTime(2026, 9, 27, 0, 28, 9, 198, DateTimeKind.Utc).AddTicks(3229),
                            IsActive = true,
                            Name = "Venta de servicios",
                            UpdatedAt = new DateTime(2026, 9, 27, 0, 28, 9, 198, DateTimeKind.Utc).AddTicks(3229)
                        },
                        new
                        {
                            Id = new Guid("e8c69902-0937-465d-83be-f1cef2e5db50"),
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ConceptType = 0,
                            CreatedAt = new DateTime(2026, 9, 27, 0, 28, 9, 198, DateTimeKind.Utc).AddTicks(3229),
                            IsActive = true,
                            Name = "Rendimientos",
                            UpdatedAt = new DateTime(2026, 9, 27, 0, 28, 9, 198, DateTimeKind.Utc).AddTicks(3229)
                        },
                        new
                        {
                            Id = new Guid("899f8e9d-2bb3-4715-bdd1-7b8545b37780"),
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ConceptType = 0,
                            CreatedAt = new DateTime(2026, 9, 27, 0, 28, 9, 198, DateTimeKind.Utc).AddTicks(3229),
                            IsActive = true,
                            Name = "Aportación de capital",
                            UpdatedAt = new DateTime(2026, 9, 27, 0, 28, 9, 198, DateTimeKind.Utc).AddTicks(3229)
                        },
                        new
                        {
                            Id = new Guid("c9777066-825e-4844-b688-a4347e9b98cd"),
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ConceptType = 0,
                            CreatedAt = new DateTime(2026, 9, 27, 0, 28, 9, 198, DateTimeKind.Utc).AddTicks(3229),
                            IsActive = true,
                            Name = "Venta de activos",
                            UpdatedAt = new DateTime(2026, 9, 27, 0, 28, 9, 198, DateTimeKind.Utc).AddTicks(3229)
                        },
                        new
                        {
                            Id = new Guid("503182de-4325-427d-81a2-12a92e429087"),
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ConceptType = 0,
                            CreatedAt = new DateTime(2026, 9, 27, 0, 28, 9, 198, DateTimeKind.Utc).AddTicks(3229),
                            IsActive = true,
                            Name = "Reembolsos",
                            UpdatedAt = new DateTime(2026, 9, 27, 0, 28, 9, 198, DateTimeKind.Utc).AddTicks(3229)
                        },
                        new
                        {
                            Id = new Guid("ab29becf-b011-4b00-ad4a-05253f13e4f0"),
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ConceptType = 1,
                            CreatedAt = new DateTime(2026, 9, 27, 0, 28, 9, 198, DateTimeKind.Utc).AddTicks(3229),
                            IsActive = true,
                            Name = "Pago de nómina",
                            UpdatedAt = new DateTime(2026, 9, 27, 0, 28, 9, 198, DateTimeKind.Utc).AddTicks(3229)
                        },
                        new
                        {
                            Id = new Guid("5de947ab-4805-4f68-adc2-50bd9648f1b1"),
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ConceptType = 1,
                            CreatedAt = new DateTime(2026, 9, 27, 0, 28, 9, 198, DateTimeKind.Utc).AddTicks(3229),
                            IsActive = true,
                            Name = "Renta de oficina",
                            UpdatedAt = new DateTime(2026, 9, 27, 0, 28, 9, 198, DateTimeKind.Utc).AddTicks(3229)
                        },
                        new
                        {
                            Id = new Guid("0d5d8a12-b23e-4fa4-9f11-d8a4b2fd9dab"),
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ConceptType = 1,
                            CreatedAt = new DateTime(2026, 9, 27, 0, 28, 9, 198, DateTimeKind.Utc).AddTicks(3229),
                            IsActive = true,
                            Name = "Servicios públicos",
                            UpdatedAt = new DateTime(2026, 9, 27, 0, 28, 9, 198, DateTimeKind.Utc).AddTicks(3229)
                        },
                        new
                        {
                            Id = new Guid("7a08746a-cff7-4613-b165-be966346d0f0"),
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ConceptType = 1,
                            CreatedAt = new DateTime(2026, 9, 27, 0, 28, 9, 198, DateTimeKind.Utc).AddTicks(3229),
                            IsActive = true,
                            Name = "Compra de equipo",
                            UpdatedAt = new DateTime(2026, 9, 27, 0, 28, 9, 198, DateTimeKind.Utc).AddTicks(3229)
                        },
                        new
                        {
                            Id = new Guid("a9c900c3-adbe-496c-866c-9eacd17d2058"),
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ConceptType = 1,
                            CreatedAt = new DateTime(2026, 9, 27, 0, 28, 9, 198, DateTimeKind.Utc).AddTicks(3229),
                            IsActive = true,
                            Name = "Licencias de software",
                            UpdatedAt = new DateTime(2026, 9, 27, 0, 28, 9, 198, DateTimeKind.Utc).AddTicks(3229)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
