// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SistemaFinanciero.Data;

#nullable disable

namespace SistemaFinanciero.Migrations
{
    [DbContext(typeof(FinancialDbContext))]
    [Migration("20260927022219_AddAccountConcept")]
    partial class AddAccountConcept
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SistemaFinanciero.Models.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountNumber")
                        .HasColumnType("text");

                    b.Property<int>("AccountType")
                        .HasColumnType("integer");

                    b.Property<string>("BankName")
                        .HasColumnType("text");

                    b.Property<string>("CardLastDigits")
                        .HasColumnType("text");

                    b.Property<string>("Clabe")
                        .HasColumnType("text");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LongDescription")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "Name")
                        .IsUnique();

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-111111111111"),
                            AccountType = 2,
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Caja Chica",
                            UpdatedAt = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("a2222222-1111-1111-1111-111111111111"),
                            AccountType = 0,
                            BankName = "Banamex",
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Cuenta Operativa",
                            UpdatedAt = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("a3333333-1111-1111-1111-111111111111"),
                            AccountType = 4,
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Fondo de Inversión",
                            UpdatedAt = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("SistemaFinanciero.Models.AccountConcept", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConceptId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ConceptId");

                    b.HasIndex("AccountId", "ConceptId")
                        .IsUnique();

                    b.ToTable("AccountConcepts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ac100001-1111-1111-1111-111111111111"),
                            AccountId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            ConceptId = new Guid("c1111115-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true
                        },
                        new
                        {
                            Id = new Guid("ac100002-1111-1111-1111-111111111111"),
                            AccountId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            ConceptId = new Guid("c2222223-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true
                        },
                        new
                        {
                            Id = new Guid("ac100003-1111-1111-1111-111111111111"),
                            AccountId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            ConceptId = new Guid("c2222224-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true
                        },
                        new
                        {
                            Id = new Guid("ac100004-1111-1111-1111-111111111111"),
                            AccountId = new Guid("a2222222-1111-1111-1111-111111111111"),
                            ConceptId = new Guid("c1111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true
                        },
                        new
                        {
                            Id = new Guid("ac100005-1111-1111-1111-111111111111"),
                            AccountId = new Guid("a2222222-1111-1111-1111-111111111111"),
                            ConceptId = new Guid("c1111113-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true
                        },
                        new
                        {
                            Id = new Guid("ac100006-1111-1111-1111-111111111111"),
                            AccountId = new Guid("a2222222-1111-1111-1111-111111111111"),
                            ConceptId = new Guid("c2222221-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true
                        },
                        new
                        {
                            Id = new Guid("ac100007-1111-1111-1111-111111111111"),
                            AccountId = new Guid("a2222222-1111-1111-1111-111111111111"),
                            ConceptId = new Guid("c2222222-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true
                        },
                        new
                        {
                            Id = new Guid("ac100008-1111-1111-1111-111111111111"),
                            AccountId = new Guid("a2222222-1111-1111-1111-111111111111"),
                            ConceptId = new Guid("c2222225-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true
                        },
                        new
                        {
                            Id = new Guid("ac100009-1111-1111-1111-111111111111"),
                            AccountId = new Guid("a3333333-1111-1111-1111-111111111111"),
                            ConceptId = new Guid("c1111112-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true
                        },
                        new
                        {
                            Id = new Guid("ac10000a-1111-1111-1111-111111111111"),
                            AccountId = new Guid("a3333333-1111-1111-1111-111111111111"),
                            ConceptId = new Guid("c1111114-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true
                        });
                });

            modelBuilder.Entity("SistemaFinanciero.Models.Concept", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<int>("ConceptType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LongDescription")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "ConceptType", "Name")
                        .IsUnique();

                    b.ToTable("Concepts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c1111111-1111-1111-1111-111111111111"),
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ConceptType = 0,
                            CreatedAt = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Venta de servicios",
                            UpdatedAt = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("c1111112-1111-1111-1111-111111111111"),
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ConceptType = 0,
                            CreatedAt = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Rendimientos",
                            UpdatedAt = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("c1111113-1111-1111-1111-111111111111"),
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ConceptType = 0,
                            CreatedAt = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Aportación de capital",
                            UpdatedAt = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("c1111114-1111-1111-1111-111111111111"),
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ConceptType = 0,
                            CreatedAt = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Venta de activos",
                            UpdatedAt = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("c1111115-1111-1111-1111-111111111111"),
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ConceptType = 0,
                            CreatedAt = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Reembolsos",
                            UpdatedAt = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("c2222221-1111-1111-1111-111111111111"),
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ConceptType = 1,
                            CreatedAt = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Pago de nómina",
                            UpdatedAt = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("c2222222-1111-1111-1111-111111111111"),
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ConceptType = 1,
                            CreatedAt = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Renta de oficina",
                            UpdatedAt = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("c2222223-1111-1111-1111-111111111111"),
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ConceptType = 1,
                            CreatedAt = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Servicios públicos",
                            UpdatedAt = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("c2222224-1111-1111-1111-111111111111"),
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ConceptType = 1,
                            CreatedAt = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Compra de equipo",
                            UpdatedAt = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("c2222225-1111-1111-1111-111111111111"),
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ConceptType = 1,
                            CreatedAt = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Licencias de software",
                            UpdatedAt = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("SistemaFinanciero.Models.AccountConcept", b =>
                {
                    b.HasOne("SistemaFinanciero.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaFinanciero.Models.Concept", "Concept")
                        .WithMany()
                        .HasForeignKey("ConceptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Concept");
                });
#pragma warning restore 612, 618
        }
    }
}
